# SPDX-License-Identifier: Apache-2.0
"""
get_logs.py
-----------
Kubernetes pod log retrieval tool.

LAYER: Tool
  Provides read-only pod log access over an SSH transport.
  All command parameters are validated and bounded before use.

  SECURITY NOTE:
    Unlike other tools in this package, get_logs.py accepts external
    parameters (pod_name, container, namespace) that are interpolated
    into the kubectl command string.  Each parameter is validated against
    a strict allowlist pattern before use to prevent shell injection.

    Kubernetes resource names follow RFC 1123 label rules:
      ^[a-z0-9][a-z0-9\\-\\.]*[a-z0-9]$  (2–253 characters)
    Container names follow the same rules.
    Namespace names follow the same rules.

    Any parameter that fails validation causes the method to return a
    ToolResult with ResultStatus.FAILURE and no command is executed.

Tools exposed:
  GetLogsTool.get_pod_logs()       — logs for a named pod/container
  GetLogsTool.get_previous_logs()  — logs from the previous (crashed) container
  GetLogsTool.get_logs_since()     — logs since a relative time (e.g. "1h")
  GetLogsTool.get_logs_tail()      — last N lines of logs
"""

from __future__ import annotations

import logging
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from tools.kubernetes.base import KubernetesTool, load_inventory, _build_connection
from utils.tool_result import ToolResult, ResultStatus
logger = logging.getLogger(__name__)

# RFC 1123 label: lowercase alphanumeric and hyphens, 1–253 chars.
# Also allows dots for pod names generated by StatefulSets and Jobs.
_K8S_NAME_PATTERN = re.compile(r'^[a-z0-9][a-z0-9\-\.]{0,251}[a-z0-9]$|^[a-z0-9]$')

# Allowed relative time suffixes for --since: e.g. 30s, 5m, 2h.
_SINCE_PATTERN = re.compile(r'^\d+[smh]$')

# Maximum number of log lines that can be requested in a single call.
# Prevents agents from inadvertently requesting enormous log buffers.
_MAX_TAIL_LINES = 5000


def _validate_name(value: str, field: str) -> str | None:
    """
    Validate a Kubernetes resource name against RFC 1123 rules.

    Returns the validated name, or None if invalid.
    Logs a warning on failure so the caller can return an error ToolResult.
    """
    if not _K8S_NAME_PATTERN.match(value):
        logger.warning(
            "Invalid Kubernetes %s name '%s'. "
            "Must match ^[a-z0-9][a-z0-9\\-\\.]*[a-z0-9]$.", field, value
        )
        return None
    return value


def _validate_since(value: str) -> str | None:
    """Validate a --since time string (e.g. '30s', '5m', '2h')."""
    if not _SINCE_PATTERN.match(value):
        logger.warning(
            "Invalid --since value '%s'. Must match ^\\d+[smh]$ (e.g. 30s, 5m, 2h).", value
        )
        return None
    return value


class GetLogsTool(KubernetesTool):
    """
    Read-only Kubernetes pod log retrieval tool.

    All methods validate input parameters before constructing kubectl
    commands.  Invalid inputs return ToolResult with FAILURE status
    and no SSH command is executed.

    AGENT USAGE NOTE:
      Log retrieval is expensive.  Agents should prefer get_warning_events()
      (from get_events.py) for triage and only call get_pod_logs() when
      the event stream points to a specific pod requiring deeper inspection.
    """

    name: str = "get_logs"
    description: str = "Retrieves pod logs by name, with optional container, time window, or tail limit."

    def execute(self, correlation_id: str | None = None) -> ToolResult:
        """
        execute() is not meaningful for GetLogsTool without a pod name.
        Agents must call get_pod_logs() directly with a validated pod name.
        """
        return ToolResult.error(
            ResultStatus.FAILURE,
            "GetLogsTool.execute() requires a pod name — call get_pod_logs() directly.",
            correlation_id=correlation_id,
        )

    def get_pod_logs(
        self,
        pod_name: str,
        namespace: str | None = None,
        container: str | None = None,
        tail_lines: int = 100,
        correlation_id: str | None = None,
    ) -> ToolResult:
        """
        Return the most recent log lines from a named pod.

        Args:
            pod_name:   Name of the pod (RFC 1123 validated).
            namespace:  Namespace override, or None for instance default.
            container:  Container name within the pod (optional; required
                        for multi-container pods).
            tail_lines: Number of most recent lines to return (max 5000).

        Returns:
            ToolResult.stdout contains the pod log output.
            ResultStatus.FAILURE if any parameter fails validation.
        """
        if not _validate_name(pod_name, "pod"):
            return ToolResult.error(
                ResultStatus.FAILURE,
                f"Invalid pod name: '{pod_name}'.",
                correlation_id=correlation_id,
            )

        tail = min(max(1, tail_lines), _MAX_TAIL_LINES)
        cmd = f"kubectl logs {pod_name} {self._ns_flag(namespace)} --tail={tail}"

        if container:
            if not _validate_name(container, "container"):
                return ToolResult.error(
                    ResultStatus.FAILURE,
                    f"Invalid container name: '{container}'.",
                    correlation_id=correlation_id,
                )
            cmd += f" -c {container}"

        return self._run(cmd, correlation_id)

    def get_previous_logs(
        self,
        pod_name: str,
        namespace: str | None = None,
        container: str | None = None,
        tail_lines: int = 100,
        correlation_id: str | None = None,
    ) -> ToolResult:
        """
        Return logs from the previous (terminated/crashed) container instance.

        Agents use this when a pod is in CrashLoopBackOff or has recently
        restarted, to capture the crash output that is no longer in the
        current container's log stream.

        Args:
            pod_name:   Name of the pod (RFC 1123 validated).
            namespace:  Namespace override, or None for instance default.
            container:  Container name (required for multi-container pods).
            tail_lines: Number of most recent lines to return (max 5000).

        Returns:
            ToolResult.stdout contains the previous container's log output.
            ResultStatus.FAILURE if any parameter fails validation.
        """
        if not _validate_name(pod_name, "pod"):
            return ToolResult.error(
                ResultStatus.FAILURE,
                f"Invalid pod name: '{pod_name}'.",
                correlation_id=correlation_id,
            )

        tail = min(max(1, tail_lines), _MAX_TAIL_LINES)
        cmd = (
            f"kubectl logs {pod_name} {self._ns_flag(namespace)} "
            f"--previous --tail={tail}"
        )

        if container:
            if not _validate_name(container, "container"):
                return ToolResult.error(
                    ResultStatus.FAILURE,
                    f"Invalid container name: '{container}'.",
                    correlation_id=correlation_id,
                )
            cmd += f" -c {container}"

        return self._run(cmd, correlation_id)

    def get_logs_since(
        self,
        pod_name: str,
        since: str,
        namespace: str | None = None,
        container: str | None = None,
        correlation_id: str | None = None,
    ) -> ToolResult:
        """
        Return logs produced within a relative time window.

        Args:
            pod_name:  Name of the pod (RFC 1123 validated).
            since:     Relative time string: e.g. '30s', '5m', '2h'.
            namespace: Namespace override, or None for instance default.
            container: Container name (optional).

        Returns:
            ToolResult.stdout contains log lines from the time window.
            ResultStatus.FAILURE if any parameter fails validation.
        """
        if not _validate_name(pod_name, "pod"):
            return ToolResult.error(
                ResultStatus.FAILURE,
                f"Invalid pod name: '{pod_name}'.",
                correlation_id=correlation_id,
            )
        if not _validate_since(since):
            return ToolResult.error(
                ResultStatus.FAILURE,
                f"Invalid --since value: '{since}'. Use format: 30s, 5m, 2h.",
                correlation_id=correlation_id,
            )

        cmd = (
            f"kubectl logs {pod_name} {self._ns_flag(namespace)} "
            f"--since={since}"
        )

        if container:
            if not _validate_name(container, "container"):
                return ToolResult.error(
                    ResultStatus.FAILURE,
                    f"Invalid container name: '{container}'.",
                    correlation_id=correlation_id,
                )
            cmd += f" -c {container}"

        return self._run(cmd, correlation_id)

    def get_logs_tail(
        self,
        pod_name: str,
        tail_lines: int,
        namespace: str | None = None,
        container: str | None = None,
        correlation_id: str | None = None,
    ) -> ToolResult:
        """
        Return the last N lines of a pod's current log stream.

        Args:
            pod_name:   Name of the pod (RFC 1123 validated).
            tail_lines: Number of lines to return (clamped to 1–5000).
            namespace:  Namespace override, or None for instance default.
            container:  Container name (optional).

        Returns:
            ToolResult.stdout contains the last N log lines.
            ResultStatus.FAILURE if any parameter fails validation.
        """
        if not _validate_name(pod_name, "pod"):
            return ToolResult.error(
                ResultStatus.FAILURE,
                f"Invalid pod name: '{pod_name}'.",
                correlation_id=correlation_id,
            )

        tail = min(max(1, tail_lines), _MAX_TAIL_LINES)
        cmd = (
            f"kubectl logs {pod_name} {self._ns_flag(namespace)} "
            f"--tail={tail}"
        )

        if container:
            if not _validate_name(container, "container"):
                return ToolResult.error(
                    ResultStatus.FAILURE,
                    f"Invalid container name: '{container}'.",
                    correlation_id=correlation_id,
                )
            cmd += f" -c {container}"

        return self._run(cmd, correlation_id)


# ---------------------------------------------------------------------------
# __main__ test harness
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s - %(message)s",
    )

    from utils.inventory_checker import InventoryError
    from tools.kubernetes.get_pods import GetPodsTool

    print("=" * 60)
    print("  GetLogsTool — test harness")
    print("=" * 60)

    try:
        config = load_inventory()
    except InventoryError as exc:
        logger.error("Inventory validation failed [%s]: %s", exc.code.value, exc)
        sys.exit(1)

    conn = _build_connection(config)
    try:
        log_tool = GetLogsTool.from_inventory(config, conn)
        pod_tool = GetPodsTool.from_inventory(config, conn)

        # ----------------------------------------------------------------
        # Test 1: Input validation — invalid pod name must return FAILURE
        # without executing any SSH command.
        # ----------------------------------------------------------------
        print("\n--- Test 1: invalid pod name rejected before SSH ---")
        result = log_tool.get_pod_logs("INVALID POD NAME!")
        assert result.status == ResultStatus.FAILURE, \
            f"Expected FAILURE, got {result.status}"
        assert result.exit_code == -1
        print(f"  PASS: status={result.status.value}, stderr='{result.stderr}'")

        # ----------------------------------------------------------------
        # Test 2: Invalid --since value rejected.
        # ----------------------------------------------------------------
        print("\n--- Test 2: invalid --since value rejected ---")
        result = log_tool.get_logs_since("some-pod", since="1day")
        assert result.status == ResultStatus.FAILURE
        print(f"  PASS: status={result.status.value}, stderr='{result.stderr}'")

        # ----------------------------------------------------------------
        # Test 3: tail_lines clamped to _MAX_TAIL_LINES.
        # ----------------------------------------------------------------
        print("\n--- Test 3: tail_lines clamped to MAX ---")

        # Discover the first running pod in the target namespace.
        pods_result = pod_tool.get_pods()
        if not pods_result.success or not pods_result.stdout.strip():
            print("  SKIP: no pods found in namespace, skipping live log tests.")
        else:
            # Parse first data line (skip header).
            lines = [l for l in pods_result.stdout.splitlines() if l and not l.startswith("NAME")]
            if lines:
                pod_name = lines[0].split()[0]
                print(f"  Using pod: {pod_name}")

                # Test 4: get_pod_logs with a valid pod.
                print(f"\n--- Test 4: get_pod_logs({pod_name}, tail=20) ---")
                result = log_tool.get_pod_logs(pod_name, tail_lines=20)
                tag = f"[{result.status.value.upper()}]"
                print(f"  {tag} ({result.duration_seconds:.2f}s)")
                print(result.stdout[:500] or result.stderr or "(no output)")

                # Test 5: get_logs_since with valid pod.
                print(f"\n--- Test 5: get_logs_since({pod_name}, since='5m') ---")
                result = log_tool.get_logs_since(pod_name, since="5m")
                tag = f"[{result.status.value.upper()}]"
                print(f"  {tag} ({result.duration_seconds:.2f}s)")
                print(result.stdout[:500] or result.stderr or "(no output)")

                # Test 6: get_previous_logs (may return error if no previous container).
                print(f"\n--- Test 6: get_previous_logs({pod_name}) ---")
                result = log_tool.get_previous_logs(pod_name, tail_lines=20)
                tag = f"[{result.status.value.upper()}]"
                print(f"  {tag} ({result.duration_seconds:.2f}s)")
                print(result.stdout[:500] or result.stderr or "(no previous container — expected)")

        print("\n" + "=" * 60)
        print("  All GetLogsTool tests complete.")
        print("=" * 60)

    finally:
        conn.disconnect()
